# Generated by Django 3.2.7 on 2021-09-18 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
